/*
 * File: app/view/DealsPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.view.DealsPanel', {
	extend: 'Ext.Panel',
	alias: 'widget.DealsPanel',

	requires: [
		'Contact.view.ListOfDeals',
		'Ext.Toolbar',
		'Ext.Button',
		'Ext.dataview.List',
		'Ext.Spacer'
	],

	config: {
		itemId: 'dealsPanel',
		minHeight: '100%',
		padding: '5 5 5 5',
		style: 'border:1px inset',
		items: [
			{
				xtype: 'toolbar',
				docked: 'top',
				ui: 'light',
				items: [
					{
						xtype: 'button',
						itemId: 'BackFromDealsPanel',
						ui: 'back',
						text: 'Back'
					}
				]
			},
			{
				xtype: 'listofdeals'
			},
			{
				xtype: 'container',
				docked: 'bottom',
				layout: 'hbox',
				items: [
					{
						xtype: 'button',
						flex: 1,
						itemId: 'UploadDeal',
						ui: 'confirm-small',
						width: 170,
						text: 'Upload New Deal'
					},
					{
						xtype: 'spacer',
						flex: 0.1,
						width: 10
					},
					{
						xtype: 'button',
						flex: 1,
						id: 'DeleteDeal',
						itemId: 'DeleteDeal',
						ui: 'decline-small',
						text: 'Delete'
					}
				]
			}
		]
	}

});