/*
 * File: app/view/Info.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.view.Info', {
	extend: 'Ext.form.Panel',
	alias: 'widget.contactinfo',

	requires: [
		'Contact.view.Picture',
		'Ext.Toolbar',
		'Ext.Button',
		'Ext.Spacer',
		'Ext.Panel',
		'Ext.field.TextArea'
	],

	config: {
		border: 5,
		minHeight: '100%',
		enableSubmissionForm: false,
		items: [
			{
				xtype: 'toolbar',
				docked: 'top',
				style: 'font-size:6vw',
				ui: 'light',
				items: [
					{
						xtype: 'button',
						itemId: 'infoBackBtn',
						style: '',
						ui: 'back',
						text: 'Back'
					},
					{
						xtype: 'button',
						docked: 'right',
						itemId: 'editButton',
						style: '',
						iconCls: 'compose'
					},
					{
						xtype: 'spacer',
						height: 11,
						width: 18
					},
					{
						xtype: 'component',
						cls: 'contact-name',
						disabled: true,
						html: '<b>First Name</b>',
						itemId: 'nameTxt',
						style: ''
					}
				]
			},
			{
				xtype: 'panel',
				border: '',
				height: '',
				maxHeight: '100%',
				minHeight: '100%',
				minWidth: '',
				padding: '5 5 5 5',
				style: 'border:1px inset',
				layout: {
					type: 'vbox',
					align: 'end'
				},
				items: [
					{
						xtype: 'contactpic',
						border: '',
						docked: 'left',
						height: 137,
						maxHeight: '100%',
						minHeight: '50%',
						minWidth: '30%',
						style: '',
						ui: 'light',
						width: 97,
						scrollable: false,
						flex: 0.5,
						layout: {
							type: 'hbox',
							align: 'start',
							pack: 'center'
						}
					},
					{
						xtype: 'panel',
						height: '',
						maxHeight: '100%',
						minHeight: '100%',
						width: '100%',
						items: [
							{
								xtype: 'textfield',
								cls: [
									'icon-phone',
									'customfield'
								],
								height: '',
								itemId: 'phoneNumber',
								maxHeight: '30%',
								maxWidth: '100%',
								minHeight: '',
								minWidth: '100%',
								width: '100%',
								clearIcon: false,
								inputCls: 'customfield',
								name: 'phoneNumber',
								readOnly: true
							},
							{
								xtype: 'spacer',
								height: '10px'
							},
							{
								xtype: 'textareafield',
								cls: [
									'icon-location',
									'customfield'
								],
								height: '100%',
								itemId: 'address',
								maxHeight: '100%',
								maxWidth: '100%',
								minHeight: '100%',
								minWidth: '100%',
								style: 'border:1 px inset',
								width: '100%',
								clearIcon: false,
								inputCls: 'customfield',
								name: 'address',
								readOnly: true,
								maxRows: 3
							}
						]
					}
				]
			},
			{
				xtype: 'button',
				handler: function(button, e) {



					var customerId = this.getParent().getRecord().get('customerId');
					var ds = Ext.StoreManager.lookup('MyDealsStore');
					ds.clearFilter() ;
					ds.filter('customerId', customerId);
					var view;

					view =Ext.Viewport.add({xtype: 'DealsPanel'});

					Ext.Viewport.setActiveItem(view);





				},
				id: 'manageDeals',
				itemId: 'manageDeals',
				text: 'Manage Deals'
			}
		]
	},

	setRecord: function(record) {

		this.callParent(arguments);


		if (record) {


		    var name = record.get('businessName');
		    //var isFavorite = record.get('isFavorite');
		    var customerId = record.get('customerId');


		   // var store = Ext.getStore('UserPreferences');

		  /* if(store.getAllCount()!==0){
		    store.each(function(rec) {
		        if(rec.get('customerId')==customerId) {
		            isFavorite = rec.get('isFavorite');
		        }
		    });
		   }*/


		//console.log(customerId + isFavorite );
		    this.down('#nameTxt').setHtml(name);
		   // console.log(store.getData());
		   /* if(isFavorite===true) {
		       this.down('#favbutton').setCls('fill-star');
		        //store.setData({'isFavorite':isFavorite});
		    }
		    else {
		        this.down('#favbutton').setCls('empty-star');





		    }*/




		  // this.down('#favoriteview')[isFavorite ? 'addCls' : 'removeCls']('x-button-pressed');
		  //  this.down('#favbutton')[isFavorite ? 'addCls' : 'removeCls']('x-button-pressed');
		    this.down('contactpic').setData(record.data);


		   // var ds = Ext.StoreManager.lookup('MyDealsStore');
		   // ds.clearFilter() ;
		   // ds.filter('customerId', customerId);
		   // this.down('listofdeals').setData(ds.getData()) ;





		    /*dealsData  = ds.getData().getAt(0);
		    var dealName = 'No Deals';
		    if(dealsData) {
		         dealName = dealsData.get('dealName');
		    }*/





		}


	}

});