/*
 * File: app/store/MyDealsStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.store.MyDealsStore', {
	extend: 'Ext.data.Store',

	requires: [
		'Contact.model.Deal',
		'Ext.data.proxy.JsonP',
		'Ext.data.reader.Json'
	],

	config: {
		autoLoad: true,
		clearOnPageLoad: false,
		model: 'Contact.model.Deal',
		storeId: 'MyDealsStore',
		proxy: {
			type: 'jsonp',
			extraParams: '{customerId}',
			url: 'http://awseb-e-t-awsebloa-6wjsk6atywko-728481327.us-west-2.elb.amazonaws.com/deals',
			reader: {
				type: 'json'
			}
		}
	}
});